// Auto-generated file. Do not edit manually.
//
package dev.threeadd.metalib.meta.protocol;

import com.github.retrooper.packetevents.protocol.entity.type.EntityTypes;
import dev.threeadd.metalib.meta.MetadataSchemaRegistry;
import dev.threeadd.metalib.meta.protocol.types.AbstractArrowMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AbstractGolemMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AbstractHorseMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AbstractNautilusMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AbstractPiglinMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AbstractSkeletonMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AbstractWindChargeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AllayMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AreaEffectCloudMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ArmadilloMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ArmorStandMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ArrowMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AvatarMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.AxolotlMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BatMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BeeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BlazeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BlockDisplayMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BoatMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BoggedMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BreezeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.BreezeWindChargeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CamelHuskMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CamelMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CatMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CaveSpiderMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ChestBoatMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ChickenMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CodMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CopperGolemMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CowMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CreakingMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CreakingTransientMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.CreeperMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.DisplayMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.DolphinMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.DonkeyMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.DragonFireballMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.DrownedMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ElderGuardianMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EndCrystalMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EnderDragonMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EndermiteMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EntityMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EvokerFangsMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EvokerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ExperienceOrbMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.EyeOfEnderMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.FireballMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.FoxMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.FrogMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.GhastMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.GiantMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.GlowItemFrameMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.GlowSquidMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.GoatMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.GuardianMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.HappyGhastMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.HoglinMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.HorseMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.HuskMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.IllusionerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.InteractionMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.IronGolemMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ItemDisplayMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ItemFrameMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.LightningBoltMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.LlamaMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.LlamaSpitMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MagmaCubeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MannequinMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MarkerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MinecartChestMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MinecartFurnaceMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MinecartHopperMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MinecartMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MinecartTNTMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.MuleMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.NautilusMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.OcelotMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.OminousItemSpawnerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PaintingMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PandaMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ParchedMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ParrotMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PhantomMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PigMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PiglinBruteMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PiglinMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PillagerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PlayerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PolarBearMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PrimedTntMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.PufferfishMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.RabbitMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.RavagerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SalmonMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SheepMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ShulkerBulletMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ShulkerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SilverfishMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SkeletonHorseMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SkeletonMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SlimeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SmallFireballMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SnifferMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SnowGolemMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SnowballMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SpectralArrowMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SpiderMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SquidMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.StrayMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.StriderMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.SulfurCubeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.TadpoleMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.TextDisplayMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.TraderLlamaMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.TropicalFishMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.TurtleMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.VexMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.VillagerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.VindicatorMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WanderingTraderMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WardenMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WindChargeMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WitchMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WitherSkeletonMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WitherSkullMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.WolfMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ZoglinMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ZombieHorseMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ZombieMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ZombieNautilusMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ZombieVillagerMetaProperties;
import dev.threeadd.metalib.meta.protocol.types.ZombifiedPiglinMetaProperties;
import org.jetbrains.annotations.ApiStatus;

@ApiStatus.Internal
public final class EntityTypeSchemas {

    public static void init() {

        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_ARROW, () -> AbstractArrowMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_GOLEM, () -> AbstractGolemMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_HORSE, () -> AbstractHorseMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_NAUTILUS, () -> AbstractNautilusMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_PIGLIN, () -> AbstractPiglinMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_SKELETON, () -> AbstractSkeletonMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ABSTRACT_WIND_CHARGE, () -> AbstractWindChargeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ALLAY, () -> AllayMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.AREA_EFFECT_CLOUD, () -> AreaEffectCloudMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ARMADILLO, () -> ArmadilloMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ARMOR_STAND, () -> ArmorStandMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ARROW, () -> ArrowMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.AVATAR, () -> AvatarMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.AXOLOTL, () -> AxolotlMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BAT, () -> BatMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BEE, () -> BeeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BLAZE, () -> BlazeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BLOCK_DISPLAY, () -> BlockDisplayMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BOAT, () -> BoatMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BOGGED, () -> BoggedMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BREEZE, () -> BreezeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.BREEZE_WIND_CHARGE, () -> BreezeWindChargeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CAMEL_HUSK, () -> CamelHuskMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CAMEL, () -> CamelMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CAT, () -> CatMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CAVE_SPIDER, () -> CaveSpiderMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CHEST_BOAT, () -> ChestBoatMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CHICKEN, () -> ChickenMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.COD, () -> CodMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.COPPER_GOLEM, () -> CopperGolemMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.COW, () -> CowMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CREAKING, () -> CreakingMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CREAKING_TRANSIENT, () -> CreakingTransientMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.CREEPER, () -> CreeperMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.DISPLAY, () -> DisplayMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.DOLPHIN, () -> DolphinMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.DONKEY, () -> DonkeyMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.DRAGON_FIREBALL, () -> DragonFireballMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.DROWNED, () -> DrownedMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ELDER_GUARDIAN, () -> ElderGuardianMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.END_CRYSTAL, () -> EndCrystalMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ENDER_DRAGON, () -> EnderDragonMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ENDERMITE, () -> EndermiteMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ENTITY, () -> EntityMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.EVOKER_FANGS, () -> EvokerFangsMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.EVOKER, () -> EvokerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.EXPERIENCE_ORB, () -> ExperienceOrbMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.EYE_OF_ENDER, () -> EyeOfEnderMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.FIREBALL, () -> FireballMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.FOX, () -> FoxMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.FROG, () -> FrogMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.GHAST, () -> GhastMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.GIANT, () -> GiantMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.GLOW_ITEM_FRAME, () -> GlowItemFrameMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.GLOW_SQUID, () -> GlowSquidMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.GOAT, () -> GoatMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.GUARDIAN, () -> GuardianMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.HAPPY_GHAST, () -> HappyGhastMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.HOGLIN, () -> HoglinMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.HORSE, () -> HorseMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.HUSK, () -> HuskMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ILLUSIONER, () -> IllusionerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.INTERACTION, () -> InteractionMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.IRON_GOLEM, () -> IronGolemMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ITEM_DISPLAY, () -> ItemDisplayMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ITEM_FRAME, () -> ItemFrameMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.LIGHTNING_BOLT, () -> LightningBoltMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.LLAMA, () -> LlamaMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.LLAMA_SPIT, () -> LlamaSpitMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MAGMA_CUBE, () -> MagmaCubeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MANNEQUIN, () -> MannequinMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MARKER, () -> MarkerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MINECART_CHEST, () -> MinecartChestMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MINECART_FURNACE, () -> MinecartFurnaceMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MINECART_HOPPER, () -> MinecartHopperMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MINECART, () -> MinecartMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MINECART_TNT, () -> MinecartTNTMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.MULE, () -> MuleMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.NAUTILUS, () -> NautilusMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.OCELOT, () -> OcelotMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.OMINOUS_ITEM_SPAWNER, () -> OminousItemSpawnerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PAINTING, () -> PaintingMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PANDA, () -> PandaMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PARCHED, () -> ParchedMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PARROT, () -> ParrotMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PHANTOM, () -> PhantomMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PIG, () -> PigMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PIGLIN_BRUTE, () -> PiglinBruteMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PIGLIN, () -> PiglinMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PILLAGER, () -> PillagerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PLAYER, () -> PlayerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.POLAR_BEAR, () -> PolarBearMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PRIMED_TNT, () -> PrimedTntMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.PUFFERFISH, () -> PufferfishMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.RABBIT, () -> RabbitMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.RAVAGER, () -> RavagerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SALMON, () -> SalmonMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SHEEP, () -> SheepMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SHULKER_BULLET, () -> ShulkerBulletMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SHULKER, () -> ShulkerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SILVERFISH, () -> SilverfishMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SKELETON_HORSE, () -> SkeletonHorseMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SKELETON, () -> SkeletonMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SLIME, () -> SlimeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SMALL_FIREBALL, () -> SmallFireballMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SNIFFER, () -> SnifferMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SNOW_GOLEM, () -> SnowGolemMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SNOWBALL, () -> SnowballMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SPECTRAL_ARROW, () -> SpectralArrowMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SPIDER, () -> SpiderMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SQUID, () -> SquidMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.STRAY, () -> StrayMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.STRIDER, () -> StriderMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.SULFUR_CUBE, () -> SulfurCubeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.TADPOLE, () -> TadpoleMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.TEXT_DISPLAY, () -> TextDisplayMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.TRADER_LLAMA, () -> TraderLlamaMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.TROPICAL_FISH, () -> TropicalFishMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.TURTLE, () -> TurtleMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.VEX, () -> VexMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.VILLAGER, () -> VillagerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.VINDICATOR, () -> VindicatorMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WANDERING_TRADER, () -> WanderingTraderMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WARDEN, () -> WardenMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WIND_CHARGE, () -> WindChargeMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WITCH, () -> WitchMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WITHER_SKELETON, () -> WitherSkeletonMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WITHER_SKULL, () -> WitherSkullMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.WOLF, () -> WolfMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ZOGLIN, () -> ZoglinMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ZOMBIE_HORSE, () -> ZombieHorseMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ZOMBIE, () -> ZombieMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ZOMBIE_NAUTILUS, () -> ZombieNautilusMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ZOMBIE_VILLAGER, () -> ZombieVillagerMetaProperties.SCHEMA);
        MetadataSchemaRegistry.registerProvider(EntityTypes.ZOMBIFIED_PIGLIN, () -> ZombifiedPiglinMetaProperties.SCHEMA);

    }

}
