plugins {
    id("metalib.java-library")
    application
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("dev.threeadd.metalib.codegen.metaproperties.MetaPropertiesCodeGen")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.packetevents.api)
    implementation(libs.adventure.api)
    implementation(libs.gson)
    implementation(libs.javapoet)
}

tasks {
    named<JavaExec>("run") {
        mainClass.set("dev.threeadd.metalib.codegen.metaproperties.MetaPropertiesCodeGen")
        args("$rootDir/api/src/autogenerated/java")
    }
}
